version: '3.0'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3307:3306"
    networks:
      - mafia_network
    container_name: mysql-container
    env_file:
      - mysql.env

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "5555:80"
    networks:
      - mafia_network
    container_name: php-container
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    env_file:
      - php.env

networks:
  mafia_network:
