version: '3.0'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mafia
      MYSQL_USER: guest
      MYSQL_PASSWORD: guest123
    networks:
      - mafia_network
    container_name: mysql-container

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "5555:80"
    networks:
      - mafia_network
    container_name: php-container
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

networks:
  mafia_network:
